include: package:mews_pedantic/analysis_options.yaml

formatter:
   page_width: 100

analyzer:
  exclude:
    - "**/*.rpc.dart"
  errors:
    invalid_annotation_target: ignore
    require_trailing_commas: ignore

dart_code_metrics:
  rules:
    avoid-barrel-files: false
    avoid-missing-interpolation: false
    avoid-passing-self-as-argument: false
    prefer-correct-handler-name: false
    match-lib-folder-structure: false
    avoid-duplicate-initializers: false
    move-variable-outside-iteration: false
    prefer-overriding-parent-equality: false # too many false positives, temporarily disabled
    avoid-unnecessary-collections: false # too many false positives, temporarily disabled
    prefer-boolean-prefixes: false
    prefer-named-parameters: false
