name: ec_client_dart
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.6.0

dependencies:
  freezed_annotation: ^2.0.1
  grpc: ^4.0.3
  protobuf: ^3.1.0
  fixnum: ^1.1.1

dev_dependencies:
  build_runner: ^2.1.10
  lints: ^5.0.0
  test: ^1.24.0
  solana: ^0.31.2+1
  freezed: ^2.0.2
