version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "pub"
    directory: "/packages/espressocash_app/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "pub"
    directory: "/packages/solana/"
    schedule:
      interval: "monthly"
