workflows:
  app-android:
    name: App Publishing Workflow
    max_build_duration: 60
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: app
    working_directory: packages/espressocash_app
    environment:
      groups:
        - common
        - google_credentials
      flutter: 3.22.2
      xcode: 15.3
      java: 17
      cocoapods: 1.13.0
      android_signing:
        - app
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.pleasecrypto.flutter

    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "android/local.properties"
      - name: Set up code signing settings on Xcode project
        script: xcode-project use-profiles
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Generate code
        script: |
          flutter pub run build_runner build --delete-conflicting-outputs
      - name: Build AAB with Flutter
        script: |
          BUILD_NUMBER=$(($PROJECT_BUILD_NUMBER + 200))
          flutter build appbundle --release \
            --build-number=$BUILD_NUMBER \
            --dart-define PROD=true \
            --dart-define SOLANA_RPC_URL=$SOLANA_RPC_URL \
            --dart-define SOLANA_WEBSOCKET_URL=$SOLANA_WEBSOCKET_URL \
            --dart-define SENTRY_DSN=$SENTRY_DSN \
            --dart-define RAMP_API_KEY=$RAMP_API_KEY \
            --dart-define KADO_API_KEY=$KADO_API_KEY \
            --dart-define GUARDARIAN_API_KEY=$GUARDARIAN_API_KEY \
            --dart-define INTERCOM_APP_ID=$INTERCOM_APP_ID \
            --dart-define INTERCOM_IOS_KEY=$INTERCOM_IOS_KEY \
            --dart-define INTERCOM_ANDROID_KEY=$INTERCOM_ANDROID_KEY \
            --dart-define MIXPANEL_TOKEN=$MIXPANEL_TOKEN
      - name: Build IPA with Flutter
        script: |
          BUILD_NUMBER=$(($PROJECT_BUILD_NUMBER + 200))
          flutter build ipa --release \
            --export-options-plist=/Users/builder/export_options.plist \
            --build-number=$BUILD_NUMBER \
            --dart-define PROD=true \
            --dart-define SOLANA_RPC_URL=$SOLANA_RPC_URL \
            --dart-define SOLANA_WEBSOCKET_URL=$SOLANA_WEBSOCKET_URL \
            --dart-define SENTRY_DSN=$SENTRY_DSN \
            --dart-define RAMP_API_KEY=$RAMP_API_KEY \
            --dart-define KADO_API_KEY=$KADO_API_KEY \
            --dart-define GUARDARIAN_API_KEY=$GUARDARIAN_API_KEY \
            --dart-define INTERCOM_APP_ID=$INTERCOM_APP_ID \
            --dart-define INTERCOM_IOS_KEY=$INTERCOM_IOS_KEY \
            --dart-define INTERCOM_ANDROID_KEY=$INTERCOM_ANDROID_KEY \
            --dart-define MIXPANEL_TOKEN=$MIXPANEL_TOKEN

    artifacts:
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log

    publishing:
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: alpha
        submit_as_draft: false
      app_store_connect:
        auth: integration
