name: dart-solana-lib

packages:
  - 'packages/**'

scripts:
  check_master:
    run: |
      melos run get \
      && melos run format \
      && melos run analyze \
      && melos run test

  get: melos exec -- dart pub get

  build: melos exec -- dart pub run build_runner build --delete-conflicting-outputs

  format: melos exec -- dart format --set-exit-if-changed -o none .

  analyze: melos exec -- dart analyze --fatal-infos .

  test: melos exec -- dart pub run test
