include: package:mews_pedantic/analysis_options.yaml

formatter:
   page_width: 100

analyzer:
  exclude:
    - "lib/src/api.dart"

dart_code_metrics:
  rules:
    prefer-boolean-prefixes: false
    prefer-static-method: false
    prefer-named-parameters: false
