targets:
  $default:
    builders:
      json_serializable:
        options:
          explicit_to_json: true

global_options:
  freezed:
    options:
      format: true
    runs_before:
      - json_serializable
