targets:
  $default:
    builders:
      json_serializable:
        options:
          explicit_to_json: true
          include_if_null: false

global_options:
  freezed:
    options:
      format: true
    runs_before:
      - json_serializable
  json_serializable:
    runs_before:
      - retrofit_generator
