name: jupiter_aggregator
description: A client for Jupiter Solana API v6
version: 0.0.5
publish_to: "none"

environment:
  sdk: ^3.0.0

dependencies:
  dio: ^5.4.0
  freezed_annotation: ^2.2.0
  retrofit: ^4.0.3

dev_dependencies:
  build_runner: ^2.3.2
  freezed: ^2.2.0
  json_serializable: ^6.5.2
  mews_pedantic: ^0.27.0
  retrofit_generator: ">=8.0.6 <10.0.0"
  test: ^1.24.0
