name: espressocash_api
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  dio: ^5.4.0
  freezed_annotation: ^2.0.1
  json_annotation: ^4.6.0
  jupiter_aggregator:
    git:
      url: https://github.com/espresso-cash/espresso-cash-public.git
      path: packages/jupiter_aggregator
  retrofit: ^4.0.3

dev_dependencies:
  build_runner: ^2.1.10
  freezed: ^2.0.2
  json_serializable: ^6.3.1
  mews_pedantic: ^0.27.0
  retrofit_generator: ">=8.0.6 <10.0.0"
