// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyDeuL6eJxuixAKyhe7GStRlZUMxpvC2A',
    appId: '1:178217337867:web:60c3ffec382ef1b4ab330e',
    messagingSenderId: '178217337867',
    projectId: 'cryptoplease-dev',
    authDomain: 'cryptoplease-dev.firebaseapp.com',
    databaseURL:
        'https://cryptoplease-dev-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cryptoplease-dev.appspot.com',
    measurementId: 'G-XX672DXR72',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnjgpI3-15xPijO7cvHUYR0dqerNRzGWg',
    appId: '1:178217337867:android:9055de8aa081bf56ab330e',
    messagingSenderId: '178217337867',
    projectId: 'cryptoplease-dev',
    databaseURL:
        'https://cryptoplease-dev-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cryptoplease-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAt67sfwN6eAkE-GTuOyo-NB-L7Avzjhn8',
    appId: '1:178217337867:ios:8798f3d0723f5598ab330e',
    messagingSenderId: '178217337867',
    projectId: 'cryptoplease-dev',
    databaseURL:
        'https://cryptoplease-dev-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cryptoplease-dev.appspot.com',
    androidClientId:
        '178217337867-2nfosmnpb7i0vgbncrjstdvjoaaiod48.apps.googleusercontent.com',
    iosClientId:
        '178217337867-ujg5flcr9lm3nugduq051la9fjn44uul.apps.googleusercontent.com',
    iosBundleId: 'com.pleasecrypto.flutter',
  );
}
