include: package:mews_pedantic/analysis_options.yaml

linter:
  rules:
    - prefer_relative_imports

analyzer:
  exclude:
    - "**/*.mocks.dart"
    - "**/*.gr.dart"
    - "test/generated/**"
    - "lib/gen/**"
    - "lib/l10n/gen/**"
    - "lib/di.config.dart"

  errors:
    always_use_package_imports: ignore
    avoid_relative_lib_imports: ignore
    deprecated_member_use_from_same_package: ignore

dart_code_metrics:
  rules:
    avoid-passing-self-as-argument: false
    prefer-overriding-parent-equality: false # too many false positives, temporarily disabled
    avoid-unnecessary-collections: false # too many false positives, temporarily disabled
    avoid-banned-imports:
      severity: error
      entries:
        - paths: [".*/models/.+\\.dart"]
          deny: [".*/(data|services|widgets|screens|ui|l10n)/.*"]
          message: "Do not import data|services|widgets|screens|ui|l10n from models"

        - paths: [".*/data/.+\\.dart"]
          deny: [".*/(services|widgets|screens|ui)/.*"]
          message: "Do not import services|widgets|screens|ui from data"

        - paths: [".*/services/.+\\.dart"]
          deny: [".*/(widgets|screens|ui|l10n)/.*"]
          message: "Do not import widgets|screens|ui|l10n from services"

        - paths: [".*/ui/.+\\.dart"]
          deny: [".*/features/.*"]
          message: "Do not import features from ui"

        - paths: [".*/utils/.+\\.dart"]
          deny: [".*/(features|ui)/.*"]
          message: "Do not import features|ui from utils"
    avoid-nullable-interpolation:
      exclude:
        - test/**
    prefer-correct-handler-name: false

  rules-exclude:
    - "**/*.gr.dart"
    - "**/generated_plugin_registrant.dart"
