include: package:mews_pedantic/analysis_options.yaml

linter:
  rules:
    - prefer_relative_imports

analyzer:
  plugins:
    - dart_code_metrics

  exclude:
    - "**/*.mocks.dart"
    - "**/*.gr.dart"
    - "test/generated/**"
    - "lib/gen/**"
    - "lib/di.config.dart"

  errors:
    always_use_package_imports: ignore
    avoid_relative_lib_imports: ignore
    deprecated_member_use_from_same_package: ignore

dart_code_metrics:
  rules:
    avoid-banned-imports:
      severity: error
      entries:
        - paths: [".*/lib/.+\\.dart"]
          deny: ["[^./]+/src/.*"]
          message: "Do not import from src directory outside of the module"

        - paths: [".*/lib/core/.+\\.dart"]
          deny: ["/(app|data|features|storybook)/"]
          message: "Core should not depend on these modules"

        - paths: [".*/lib/data/.+\\.dart"]
          deny: ["/(app|storybook|ui)/"]
          message: "Data should not depend on these modules"

        - paths: [".*/lib/features/.+\\.dart"]
          deny: ["/(app|storybook)/"]
          message: "Features should not depend on these modules"

        - paths: [".*/lib/ui/.+\\.dart"]
          deny: ["/(app|data|features|storybook)/"]
          message: "UI should not depend on these modules"

  rules-exclude:
    - "**/*.gr.dart"
    - "**/generated_plugin_registrant.dart"
