import 'package:auto_route/auto_route.dart';
import 'package:cryptoplease/app/routes.gr.dart';
import 'package:cryptoplease/app/screens/authenticated/components/navigation_bar/navigation_bar.dart';
import 'package:cryptoplease/features/profile/components/menu_button.dart';
import 'package:cryptoplease/gen/assets.gen.dart';
import 'package:cryptoplease_ui/cryptoplease_ui.dart';
import 'package:flutter/material.dart';

class MenuSection extends StatelessWidget {
  const MenuSection({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) => Expanded(
        child: Material(
          color: CpColors.greyBackground,
          child: ListView(
            physics: const BouncingScrollPhysics(),
            padding: const EdgeInsets.symmetric(horizontal: 16),
            children: [
              _Section(
                title: 'Security',
                children: [
                  MenuButton(
                    title: 'App Lock',
                    description: 'Temporarily lock the app',
                    icon: Assets.icons.lock,
                    onTap: () => context.router.push(
                      const AppLockSetupFlowRoute(),
                    ),
                  ),
                  MenuButton(
                    title: 'View secret recovery phrase',
                    description: 'Words generated by your crypto wallet',
                    icon: Assets.icons.secret,
                    onTap: () => context.router.push(
                      const BackupPhraseFlowRoute(),
                    ),
                  ),
                ],
              ),
              _Section(
                title: 'Your Account',
                children: [
                  MenuButton(
                    title: 'Edit Profile',
                    description: 'Make changes to your current profile',
                    icon: Assets.icons.visibility,
                    onTap: () => context.router.push(
                      const EditProfileRoute(),
                    ),
                  ),
                  MenuButton(
                    title: 'Learning About Crypto',
                    description: 'Get help with all things crypto',
                    icon: Assets.icons.info,
                    onTap: () => context.router.push(
                      const HelpRoute(),
                    ),
                  ),
                ],
              ),
              const SizedBox(height: cpNavigationBarheight + 16)
            ],
          ),
        ),
      );
}

class _Section extends StatelessWidget {
  const _Section({
    Key? key,
    required this.title,
    required this.children,
  }) : super(key: key);

  final String title;
  final List<Widget> children;

  @override
  Widget build(BuildContext context) => Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Padding(
            padding: const EdgeInsets.only(top: 16, left: 16, bottom: 4),
            child: Text(
              title.toUpperCase(),
              style: const TextStyle(
                fontSize: 13,
                fontWeight: FontWeight.bold,
                color: CpColors.menuPrimaryTextColor,
              ),
            ),
          ),
          ClipRRect(
            borderRadius: const BorderRadius.all(Radius.circular(30)),
            child: Material(
              color: Colors.white,
              child: ListView(
                padding: const EdgeInsets.symmetric(vertical: 16),
                physics: const NeverScrollableScrollPhysics(),
                shrinkWrap: true,
                children: children,
              ),
            ),
          ),
        ],
      );
}
