import 'package:freezed_annotation/freezed_annotation.dart';

part 'filter.freezed.dart';
part 'filter.g.dart';

@freezed
class Filter with _$Filter {
  const factory Filter.dataSize(int dataSize) = DataSizeFilter;

  const factory Filter.memcmp({
    required int offset,
    required String bytes,
  }) = MemcmpFilter;

  // WARNING: this is only needed so that json code is generated by freezed
  factory Filter.fromJson(Map<String, dynamic> json) => _$FilterFromJson(json);
}
