// Mocks generated by Mockito 5.4.0 from annotations
// in solana_mobile_wallet/test/scenario_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:typed_data' as _i9;

import 'package:mockito/mockito.dart' as _i1;
import 'package:solana_mobile_wallet/src/events/deauthorize.dart' as _i8;
import 'package:solana_mobile_wallet/src/requests/authorize.dart' as _i4;
import 'package:solana_mobile_wallet/src/requests/reauthorize.dart' as _i5;
import 'package:solana_mobile_wallet/src/requests/sign_and_send_transactions.dart'
    as _i7;
import 'package:solana_mobile_wallet/src/requests/sign_transactions.dart'
    as _i6;
import 'package:solana_mobile_wallet/src/scenario.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeScenarioCallbacks_0 extends _i1.SmartFake
    implements _i2.ScenarioCallbacks {
  _FakeScenarioCallbacks_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ScenarioCallbacks].
///
/// See the documentation for Mockito's code generation for more information.
class MockScenarioCallbacks extends _i1.Mock implements _i2.ScenarioCallbacks {
  MockScenarioCallbacks() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void onScenarioReady(_i2.Scenario? scenario) => super.noSuchMethod(
        Invocation.method(
          #onScenarioReady,
          [scenario],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void onScenarioServingClients() => super.noSuchMethod(
        Invocation.method(
          #onScenarioServingClients,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void onScenarioServingComplete() => super.noSuchMethod(
        Invocation.method(
          #onScenarioServingComplete,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void onScenarioComplete() => super.noSuchMethod(
        Invocation.method(
          #onScenarioComplete,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void onScenarioError() => super.noSuchMethod(
        Invocation.method(
          #onScenarioError,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void onScenarioTeardownComplete() => super.noSuchMethod(
        Invocation.method(
          #onScenarioTeardownComplete,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void onLowPowerAndNoConnection() => super.noSuchMethod(
        Invocation.method(
          #onLowPowerAndNoConnection,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i3.Future<_i4.AuthorizeResult?> onAuthorizeRequest(
          _i4.AuthorizeRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #onAuthorizeRequest,
          [request],
        ),
        returnValue: _i3.Future<_i4.AuthorizeResult?>.value(),
      ) as _i3.Future<_i4.AuthorizeResult?>);
  @override
  _i3.Future<bool> onReauthorizeRequest(_i5.ReauthorizeRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #onReauthorizeRequest,
          [request],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
  @override
  _i3.Future<_i6.SignedPayloadResult?> onSignTransactionsRequest(
          _i6.SignTransactionsRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #onSignTransactionsRequest,
          [request],
        ),
        returnValue: _i3.Future<_i6.SignedPayloadResult?>.value(),
      ) as _i3.Future<_i6.SignedPayloadResult?>);
  @override
  _i3.Future<_i6.SignedPayloadResult?> onSignMessagesRequest(
          _i6.SignMessagesRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #onSignMessagesRequest,
          [request],
        ),
        returnValue: _i3.Future<_i6.SignedPayloadResult?>.value(),
      ) as _i3.Future<_i6.SignedPayloadResult?>);
  @override
  _i3.Future<_i7.SignaturesResult?> onSignAndSendTransactionsRequest(
          _i7.SignAndSendTransactionsRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #onSignAndSendTransactionsRequest,
          [request],
        ),
        returnValue: _i3.Future<_i7.SignaturesResult?>.value(),
      ) as _i3.Future<_i7.SignaturesResult?>);
  @override
  _i3.Future<void> onDeauthorizeEvent(_i8.DeauthorizeEvent? event) =>
      (super.noSuchMethod(
        Invocation.method(
          #onDeauthorizeEvent,
          [event],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [Scenario].
///
/// See the documentation for Mockito's code generation for more information.
class MockScenario extends _i1.Mock implements _i2.Scenario {
  MockScenario() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get id => (super.noSuchMethod(
        Invocation.getter(#id),
        returnValue: 0,
      ) as int);
  @override
  _i9.Uint8List get associationPublicKey => (super.noSuchMethod(
        Invocation.getter(#associationPublicKey),
        returnValue: _i9.Uint8List(0),
      ) as _i9.Uint8List);
  @override
  _i2.ScenarioCallbacks get callbacks => (super.noSuchMethod(
        Invocation.getter(#callbacks),
        returnValue: _FakeScenarioCallbacks_0(
          this,
          Invocation.getter(#callbacks),
        ),
      ) as _i2.ScenarioCallbacks);
  @override
  void start() => super.noSuchMethod(
        Invocation.method(
          #start,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void close() => super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
