// Autogenerated from Pigeon (v3.2.6), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import
import 'dart:async';
import 'dart:typed_data' show Uint8List, Int32List, Int64List, Float64List;

import 'package:flutter/foundation.dart' show WriteBuffer, ReadBuffer;
import 'package:flutter/services.dart';

enum MobileWalletAdapterServerException {
  requestDeclined,
  invalidPayloads,
  tooManyPayloads,
  authorizationNotValid,
  notSubmitted,
}

class AuthorizeRequestDto {
  AuthorizeRequestDto({
    this.identityName,
    this.identityUri,
    this.iconUri,
  });

  String? identityName;
  String? identityUri;
  String? iconUri;

  Object encode() {
    final Map<Object?, Object?> pigeonMap = <Object?, Object?>{};
    pigeonMap['identityName'] = identityName;
    pigeonMap['identityUri'] = identityUri;
    pigeonMap['iconUri'] = iconUri;
    return pigeonMap;
  }

  static AuthorizeRequestDto decode(Object message) {
    final Map<Object?, Object?> pigeonMap = message as Map<Object?, Object?>;
    return AuthorizeRequestDto(
      identityName: pigeonMap['identityName'] as String?,
      identityUri: pigeonMap['identityUri'] as String?,
      iconUri: pigeonMap['iconUri'] as String?,
    );
  }
}

class AuthorizeResultDto {
  AuthorizeResultDto({
    required this.publicKey,
    this.accountLabel,
    this.walletUriBase,
    this.scope,
  });

  Uint8List publicKey;
  String? accountLabel;
  String? walletUriBase;
  Uint8List? scope;

  Object encode() {
    final Map<Object?, Object?> pigeonMap = <Object?, Object?>{};
    pigeonMap['publicKey'] = publicKey;
    pigeonMap['accountLabel'] = accountLabel;
    pigeonMap['walletUriBase'] = walletUriBase;
    pigeonMap['scope'] = scope;
    return pigeonMap;
  }

  static AuthorizeResultDto decode(Object message) {
    final Map<Object?, Object?> pigeonMap = message as Map<Object?, Object?>;
    return AuthorizeResultDto(
      publicKey: pigeonMap['publicKey']! as Uint8List,
      accountLabel: pigeonMap['accountLabel'] as String?,
      walletUriBase: pigeonMap['walletUriBase'] as String?,
      scope: pigeonMap['scope'] as Uint8List?,
    );
  }
}

class ReauthorizeRequestDto {
  ReauthorizeRequestDto({
    this.identityName,
    this.identityUri,
    this.iconRelativeUri,
    required this.cluster,
    required this.authorizationScope,
  });

  String? identityName;
  String? identityUri;
  String? iconRelativeUri;
  String cluster;
  Uint8List authorizationScope;

  Object encode() {
    final Map<Object?, Object?> pigeonMap = <Object?, Object?>{};
    pigeonMap['identityName'] = identityName;
    pigeonMap['identityUri'] = identityUri;
    pigeonMap['iconRelativeUri'] = iconRelativeUri;
    pigeonMap['cluster'] = cluster;
    pigeonMap['authorizationScope'] = authorizationScope;
    return pigeonMap;
  }

  static ReauthorizeRequestDto decode(Object message) {
    final Map<Object?, Object?> pigeonMap = message as Map<Object?, Object?>;
    return ReauthorizeRequestDto(
      identityName: pigeonMap['identityName'] as String?,
      identityUri: pigeonMap['identityUri'] as String?,
      iconRelativeUri: pigeonMap['iconRelativeUri'] as String?,
      cluster: pigeonMap['cluster']! as String,
      authorizationScope: pigeonMap['authorizationScope']! as Uint8List,
    );
  }
}

class SignedPayloadsResultDto {
  SignedPayloadsResultDto({
    this.payloads,
    this.error,
    this.validPayloads,
  });

  List<Uint8List?>? payloads;
  MobileWalletAdapterServerException? error;
  List<bool?>? validPayloads;

  Object encode() {
    final Map<Object?, Object?> pigeonMap = <Object?, Object?>{};
    pigeonMap['payloads'] = payloads;
    pigeonMap['error'] = error?.index;
    pigeonMap['validPayloads'] = validPayloads;
    return pigeonMap;
  }

  static SignedPayloadsResultDto decode(Object message) {
    final Map<Object?, Object?> pigeonMap = message as Map<Object?, Object?>;
    return SignedPayloadsResultDto(
      payloads: (pigeonMap['payloads'] as List<Object?>?)?.cast<Uint8List?>(),
      error: pigeonMap['error'] != null
          ? MobileWalletAdapterServerException
              .values[pigeonMap['error']! as int]
          : null,
      validPayloads:
          (pigeonMap['validPayloads'] as List<Object?>?)?.cast<bool?>(),
    );
  }
}

class SignTransactionsRequestDto {
  SignTransactionsRequestDto({
    required this.payloads,
    this.identityName,
    this.identityUri,
    this.iconRelativeUri,
    required this.cluster,
    required this.authorizationScope,
  });

  List<Uint8List?> payloads;
  String? identityName;
  String? identityUri;
  String? iconRelativeUri;
  String cluster;
  Uint8List authorizationScope;

  Object encode() {
    final Map<Object?, Object?> pigeonMap = <Object?, Object?>{};
    pigeonMap['payloads'] = payloads;
    pigeonMap['identityName'] = identityName;
    pigeonMap['identityUri'] = identityUri;
    pigeonMap['iconRelativeUri'] = iconRelativeUri;
    pigeonMap['cluster'] = cluster;
    pigeonMap['authorizationScope'] = authorizationScope;
    return pigeonMap;
  }

  static SignTransactionsRequestDto decode(Object message) {
    final Map<Object?, Object?> pigeonMap = message as Map<Object?, Object?>;
    return SignTransactionsRequestDto(
      payloads: (pigeonMap['payloads'] as List<Object?>?)!.cast<Uint8List?>(),
      identityName: pigeonMap['identityName'] as String?,
      identityUri: pigeonMap['identityUri'] as String?,
      iconRelativeUri: pigeonMap['iconRelativeUri'] as String?,
      cluster: pigeonMap['cluster']! as String,
      authorizationScope: pigeonMap['authorizationScope']! as Uint8List,
    );
  }
}

class SignMessagesRequestDto {
  SignMessagesRequestDto({
    required this.payloads,
    this.identityName,
    this.identityUri,
    this.iconRelativeUri,
    required this.cluster,
    required this.authorizationScope,
  });

  List<Uint8List?> payloads;
  String? identityName;
  String? identityUri;
  String? iconRelativeUri;
  String cluster;
  Uint8List authorizationScope;

  Object encode() {
    final Map<Object?, Object?> pigeonMap = <Object?, Object?>{};
    pigeonMap['payloads'] = payloads;
    pigeonMap['identityName'] = identityName;
    pigeonMap['identityUri'] = identityUri;
    pigeonMap['iconRelativeUri'] = iconRelativeUri;
    pigeonMap['cluster'] = cluster;
    pigeonMap['authorizationScope'] = authorizationScope;
    return pigeonMap;
  }

  static SignMessagesRequestDto decode(Object message) {
    final Map<Object?, Object?> pigeonMap = message as Map<Object?, Object?>;
    return SignMessagesRequestDto(
      payloads: (pigeonMap['payloads'] as List<Object?>?)!.cast<Uint8List?>(),
      identityName: pigeonMap['identityName'] as String?,
      identityUri: pigeonMap['identityUri'] as String?,
      iconRelativeUri: pigeonMap['iconRelativeUri'] as String?,
      cluster: pigeonMap['cluster']! as String,
      authorizationScope: pigeonMap['authorizationScope']! as Uint8List,
    );
  }
}

class SignAndSendTransactionsRequestDto {
  SignAndSendTransactionsRequestDto({
    this.minContextSlot,
    required this.transactions,
    required this.publicKey,
    this.identityName,
    this.identityUri,
    this.iconRelativeUri,
    required this.cluster,
    required this.authorizationScope,
  });

  int? minContextSlot;
  List<Uint8List?> transactions;
  Uint8List publicKey;
  String? identityName;
  String? identityUri;
  String? iconRelativeUri;
  String cluster;
  Uint8List authorizationScope;

  Object encode() {
    final Map<Object?, Object?> pigeonMap = <Object?, Object?>{};
    pigeonMap['minContextSlot'] = minContextSlot;
    pigeonMap['transactions'] = transactions;
    pigeonMap['publicKey'] = publicKey;
    pigeonMap['identityName'] = identityName;
    pigeonMap['identityUri'] = identityUri;
    pigeonMap['iconRelativeUri'] = iconRelativeUri;
    pigeonMap['cluster'] = cluster;
    pigeonMap['authorizationScope'] = authorizationScope;
    return pigeonMap;
  }

  static SignAndSendTransactionsRequestDto decode(Object message) {
    final Map<Object?, Object?> pigeonMap = message as Map<Object?, Object?>;
    return SignAndSendTransactionsRequestDto(
      minContextSlot: pigeonMap['minContextSlot'] as int?,
      transactions:
          (pigeonMap['transactions'] as List<Object?>?)!.cast<Uint8List?>(),
      publicKey: pigeonMap['publicKey']! as Uint8List,
      identityName: pigeonMap['identityName'] as String?,
      identityUri: pigeonMap['identityUri'] as String?,
      iconRelativeUri: pigeonMap['iconRelativeUri'] as String?,
      cluster: pigeonMap['cluster']! as String,
      authorizationScope: pigeonMap['authorizationScope']! as Uint8List,
    );
  }
}

class SignaturesResultDto {
  SignaturesResultDto({
    this.signatures,
    this.error,
    this.validSignatures,
  });

  List<Uint8List?>? signatures;
  MobileWalletAdapterServerException? error;
  List<bool?>? validSignatures;

  Object encode() {
    final Map<Object?, Object?> pigeonMap = <Object?, Object?>{};
    pigeonMap['signatures'] = signatures;
    pigeonMap['error'] = error?.index;
    pigeonMap['validSignatures'] = validSignatures;
    return pigeonMap;
  }

  static SignaturesResultDto decode(Object message) {
    final Map<Object?, Object?> pigeonMap = message as Map<Object?, Object?>;
    return SignaturesResultDto(
      signatures:
          (pigeonMap['signatures'] as List<Object?>?)?.cast<Uint8List?>(),
      error: pigeonMap['error'] != null
          ? MobileWalletAdapterServerException
              .values[pigeonMap['error']! as int]
          : null,
      validSignatures:
          (pigeonMap['validSignatures'] as List<Object?>?)?.cast<bool?>(),
    );
  }
}

class _ApiFlutterCodec extends StandardMessageCodec {
  const _ApiFlutterCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is AuthorizeRequestDto) {
      buffer.putUint8(128);
      writeValue(buffer, value.encode());
    } else if (value is AuthorizeResultDto) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else if (value is ReauthorizeRequestDto) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else if (value is SignAndSendTransactionsRequestDto) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else if (value is SignMessagesRequestDto) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else if (value is SignTransactionsRequestDto) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    } else if (value is SignaturesResultDto) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    } else if (value is SignedPayloadsResultDto) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 128:
        return AuthorizeRequestDto.decode(readValue(buffer)!);

      case 129:
        return AuthorizeResultDto.decode(readValue(buffer)!);

      case 130:
        return ReauthorizeRequestDto.decode(readValue(buffer)!);

      case 131:
        return SignAndSendTransactionsRequestDto.decode(readValue(buffer)!);

      case 132:
        return SignMessagesRequestDto.decode(readValue(buffer)!);

      case 133:
        return SignTransactionsRequestDto.decode(readValue(buffer)!);

      case 134:
        return SignaturesResultDto.decode(readValue(buffer)!);

      case 135:
        return SignedPayloadsResultDto.decode(readValue(buffer)!);

      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

abstract class ApiFlutter {
  static const MessageCodec<Object?> codec = _ApiFlutterCodec();

  void onScenarioReady(int id);
  void onScenarioServingClients(int id);
  void onScenarioServingComplete(int id);
  void onScenarioComplete(int id);
  void onScenarioError(int id);
  void onScenarioTeardownComplete(int id);
  Future<AuthorizeResultDto?> authorize(AuthorizeRequestDto request, int id);
  Future<bool> reauthorize(ReauthorizeRequestDto request, int id);
  Future<SignedPayloadsResultDto?> signTransactions(
      SignTransactionsRequestDto request, int id);
  Future<SignedPayloadsResultDto?> signMessages(
      SignMessagesRequestDto request, int id);
  Future<SignaturesResultDto?> signAndSendTransactions(
      SignAndSendTransactionsRequestDto request, int id);
  static void setup(ApiFlutter? api, {BinaryMessenger? binaryMessenger}) {
    {
      final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.ApiFlutter.onScenarioReady', codec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object? message) async {
          assert(message != null,
              'Argument for dev.flutter.pigeon.ApiFlutter.onScenarioReady was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final int? arg_id = (args[0] as int?);
          assert(arg_id != null,
              'Argument for dev.flutter.pigeon.ApiFlutter.onScenarioReady was null, expected non-null int.');
          api.onScenarioReady(arg_id!);
          return;
        });
      }
    }
    {
      final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.ApiFlutter.onScenarioServingClients', codec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object? message) async {
          assert(message != null,
              'Argument for dev.flutter.pigeon.ApiFlutter.onScenarioServingClients was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final int? arg_id = (args[0] as int?);
          assert(arg_id != null,
              'Argument for dev.flutter.pigeon.ApiFlutter.onScenarioServingClients was null, expected non-null int.');
          api.onScenarioServingClients(arg_id!);
          return;
        });
      }
    }
    {
      final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.ApiFlutter.onScenarioServingComplete', codec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object? message) async {
          assert(message != null,
              'Argument for dev.flutter.pigeon.ApiFlutter.onScenarioServingComplete was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final int? arg_id = (args[0] as int?);
          assert(arg_id != null,
              'Argument for dev.flutter.pigeon.ApiFlutter.onScenarioServingComplete was null, expected non-null int.');
          api.onScenarioServingComplete(arg_id!);
          return;
        });
      }
    }
    {
      final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.ApiFlutter.onScenarioComplete', codec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object? message) async {
          assert(message != null,
              'Argument for dev.flutter.pigeon.ApiFlutter.onScenarioComplete was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final int? arg_id = (args[0] as int?);
          assert(arg_id != null,
              'Argument for dev.flutter.pigeon.ApiFlutter.onScenarioComplete was null, expected non-null int.');
          api.onScenarioComplete(arg_id!);
          return;
        });
      }
    }
    {
      final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.ApiFlutter.onScenarioError', codec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object? message) async {
          assert(message != null,
              'Argument for dev.flutter.pigeon.ApiFlutter.onScenarioError was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final int? arg_id = (args[0] as int?);
          assert(arg_id != null,
              'Argument for dev.flutter.pigeon.ApiFlutter.onScenarioError was null, expected non-null int.');
          api.onScenarioError(arg_id!);
          return;
        });
      }
    }
    {
      final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.ApiFlutter.onScenarioTeardownComplete', codec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object? message) async {
          assert(message != null,
              'Argument for dev.flutter.pigeon.ApiFlutter.onScenarioTeardownComplete was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final int? arg_id = (args[0] as int?);
          assert(arg_id != null,
              'Argument for dev.flutter.pigeon.ApiFlutter.onScenarioTeardownComplete was null, expected non-null int.');
          api.onScenarioTeardownComplete(arg_id!);
          return;
        });
      }
    }
    {
      final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.ApiFlutter.authorize', codec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object? message) async {
          assert(message != null,
              'Argument for dev.flutter.pigeon.ApiFlutter.authorize was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final AuthorizeRequestDto? arg_request =
              (args[0] as AuthorizeRequestDto?);
          assert(arg_request != null,
              'Argument for dev.flutter.pigeon.ApiFlutter.authorize was null, expected non-null AuthorizeRequestDto.');
          final int? arg_id = (args[1] as int?);
          assert(arg_id != null,
              'Argument for dev.flutter.pigeon.ApiFlutter.authorize was null, expected non-null int.');
          final AuthorizeResultDto? output =
              await api.authorize(arg_request!, arg_id!);
          return output;
        });
      }
    }
    {
      final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.ApiFlutter.reauthorize', codec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object? message) async {
          assert(message != null,
              'Argument for dev.flutter.pigeon.ApiFlutter.reauthorize was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final ReauthorizeRequestDto? arg_request =
              (args[0] as ReauthorizeRequestDto?);
          assert(arg_request != null,
              'Argument for dev.flutter.pigeon.ApiFlutter.reauthorize was null, expected non-null ReauthorizeRequestDto.');
          final int? arg_id = (args[1] as int?);
          assert(arg_id != null,
              'Argument for dev.flutter.pigeon.ApiFlutter.reauthorize was null, expected non-null int.');
          final bool output = await api.reauthorize(arg_request!, arg_id!);
          return output;
        });
      }
    }
    {
      final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.ApiFlutter.signTransactions', codec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object? message) async {
          assert(message != null,
              'Argument for dev.flutter.pigeon.ApiFlutter.signTransactions was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final SignTransactionsRequestDto? arg_request =
              (args[0] as SignTransactionsRequestDto?);
          assert(arg_request != null,
              'Argument for dev.flutter.pigeon.ApiFlutter.signTransactions was null, expected non-null SignTransactionsRequestDto.');
          final int? arg_id = (args[1] as int?);
          assert(arg_id != null,
              'Argument for dev.flutter.pigeon.ApiFlutter.signTransactions was null, expected non-null int.');
          final SignedPayloadsResultDto? output =
              await api.signTransactions(arg_request!, arg_id!);
          return output;
        });
      }
    }
    {
      final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.ApiFlutter.signMessages', codec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object? message) async {
          assert(message != null,
              'Argument for dev.flutter.pigeon.ApiFlutter.signMessages was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final SignMessagesRequestDto? arg_request =
              (args[0] as SignMessagesRequestDto?);
          assert(arg_request != null,
              'Argument for dev.flutter.pigeon.ApiFlutter.signMessages was null, expected non-null SignMessagesRequestDto.');
          final int? arg_id = (args[1] as int?);
          assert(arg_id != null,
              'Argument for dev.flutter.pigeon.ApiFlutter.signMessages was null, expected non-null int.');
          final SignedPayloadsResultDto? output =
              await api.signMessages(arg_request!, arg_id!);
          return output;
        });
      }
    }
    {
      final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.ApiFlutter.signAndSendTransactions', codec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object? message) async {
          assert(message != null,
              'Argument for dev.flutter.pigeon.ApiFlutter.signAndSendTransactions was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final SignAndSendTransactionsRequestDto? arg_request =
              (args[0] as SignAndSendTransactionsRequestDto?);
          assert(arg_request != null,
              'Argument for dev.flutter.pigeon.ApiFlutter.signAndSendTransactions was null, expected non-null SignAndSendTransactionsRequestDto.');
          final int? arg_id = (args[1] as int?);
          assert(arg_id != null,
              'Argument for dev.flutter.pigeon.ApiFlutter.signAndSendTransactions was null, expected non-null int.');
          final SignaturesResultDto? output =
              await api.signAndSendTransactions(arg_request!, arg_id!);
          return output;
        });
      }
    }
  }
}

class _ApiHostCodec extends StandardMessageCodec {
  const _ApiHostCodec();
}

class ApiHost {
  /// Constructor for [ApiHost].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  ApiHost({BinaryMessenger? binaryMessenger})
      : _binaryMessenger = binaryMessenger;

  final BinaryMessenger? _binaryMessenger;

  static const MessageCodec<Object?> codec = _ApiHostCodec();

  Future<void> start(int arg_id) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.ApiHost.start', codec,
        binaryMessenger: _binaryMessenger);
    final Map<Object?, Object?>? replyMap =
        await channel.send(<Object?>[arg_id]) as Map<Object?, Object?>?;
    if (replyMap == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyMap['error'] != null) {
      final Map<Object?, Object?> error =
          (replyMap['error'] as Map<Object?, Object?>?)!;
      throw PlatformException(
        code: (error['code'] as String?)!,
        message: error['message'] as String?,
        details: error['details'],
      );
    } else {
      return;
    }
  }

  Future<void> close(int arg_id) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.ApiHost.close', codec,
        binaryMessenger: _binaryMessenger);
    final Map<Object?, Object?>? replyMap =
        await channel.send(<Object?>[arg_id]) as Map<Object?, Object?>?;
    if (replyMap == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyMap['error'] != null) {
      final Map<Object?, Object?> error =
          (replyMap['error'] as Map<Object?, Object?>?)!;
      throw PlatformException(
        code: (error['code'] as String?)!,
        message: error['message'] as String?,
        details: error['details'],
      );
    } else {
      return;
    }
  }
}
